package generics.watercolors;

public enum Watercolors {
	ZINC, LEM0N_YEEL0W, MEDIUM_YELLOW, DEEP_YELLOW, ORANGE,
			BRILLIANT_RED, CRIMSON, MAGENTA, R0SE_MADDER, VIOLET,
			CERULEAN_BLUE_HUE, PHTHALO_BLUE, ULTRAMARINE,
			COBALT__BLUE_HUE, PERMANENT_GREEN , VIRIDIAN_HUE ,
			SAP_GREEN, YELLOW_OCHRE, BURNT_SIENNA, RAW_UMBER,
			BURNT_UMBER, FAYNES_GRAY, IV0RY_BLACK
}
